let todos=[];
Office.onReady(function(){const v=document.getElementById("btnVoltar"),h=document.getElementById("btnHistorico"),a=document.getElementById("btnAtualizar"),p=document.getElementById("btnAplicar"),l=document.getElementById("btnLimpar");if(v)v.addEventListener("click",()=>window.location.assign("taskpane.html"));if(h)h.addEventListener("click",()=>window.location.assign("historico.html"));if(a)a.addEventListener("click",carregar);if(p)p.addEventListener("click",atualizarResumo);if(l)l.addEventListener("click",limparFiltros);carregar()});
function n(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase()}
function idx(m,a){for(const x of a){const k=n(x);if(m[k]!==undefined)return m[k]}return -1}
function cab(v){for(let i=0;i<Math.min(v.length,30);i++){const m={};(v[i]||[]).forEach((x,j)=>{if(String(x??"").trim())m[n(x)]=j});if(idx(m,["EMPRESA"])!==-1&&idx(m,["DATA"])!==-1)return{linha:i,mapa:m}}return null}
function val(r,m,a){const i=idx(m,a);return i<0?"":r[i]??""}
function dt(v){if(typeof v==="number")return Date.UTC(1899,11,30)+v*86400000;const d=new Date(v);return isNaN(d)?0:d.getTime()}
async function carregar(){const st=document.getElementById("status");if(st){st.textContent="● Carregando resumo...";st.className="status aviso";}try{todos=[];await Excel.run(async c=>{for(const nome of["Email","SMS"]){const s=c.workbook.worksheets.getItem(nome),u=s.getUsedRangeOrNullObject(true);u.load(["values","isNullObject"]);await c.sync();if(u.isNullObject)continue;const h=cab(u.values);if(!h)continue;for(let i=h.linha+1;i<u.values.length;i++){const r=u.values[i]||[];if(!String(val(r,h.mapa,["EMPRESA"])).trim())continue;todos.push({tipo:nome,data:val(r,h.mapa,["DATA"]),qtde:Number(val(r,h.mapa,["QTDE"]))||0})}}});atualizarResumo();if(st){st.textContent="✓ Resumo atualizado.";st.className="status sucesso";}}catch(e){const x=document.getElementById("status");if(x){x.textContent=e.message||"Erro ao carregar resumo.";x.className="status erro"}}}
function atualizarResumo(){const di=document.getElementById("dataInicio")?.value||"",df=document.getElementById("dataFim")?.value||"";const f=todos.filter(r=>(!di||dt(r.data)>=new Date(di+"T00:00:00").getTime())&&(!df||dt(r.data)<=new Date(df+"T23:59:59").getTime()));let er=0,sr=0,eq=0,sq=0;f.forEach(r=>r.tipo==="Email"?(er++,eq+=r.qtde):(sr++,sq+=r.qtde));document.getElementById("emailReg").textContent=er;document.getElementById("smsReg").textContent=sr;document.getElementById("emailQtd").textContent=eq.toLocaleString("pt-BR");document.getElementById("smsQtd").textContent=sq.toLocaleString("pt-BR");document.getElementById("hoje").textContent=f.length;document.getElementById("total").textContent=f.length}
function limparFiltros(){const a=document.getElementById("dataInicio"),b=document.getElementById("dataFim");if(a)a.value="";if(b)b.value="";atualizarResumo()}